### ISSUE TITLE
Content-type not set for _bulk?

### ISSUE THREAD

**Issue by faxm0dem** [mpenet/spandex#28]
Hi,

I'm getting the following in the logs:

```
request [POST http://foobar:9200/_bulk] returned 1 warnings: [299 Elasticsearch-5.3.2-3068195 "Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header." "Sat, 28 Oct 2017 06:55:14 GMT"]
```

Here's the code call:

```
(es/request conn {:url "_bulk" :body (es/chunks->body bulk-create-items) :method :post})
```

do I have to add `:content-type "application/json"` ?

**Comment by mpenet** [comment]
Hi,

Can you tell me what version you re using? It sounds like something we fixed recently.

**Comment by mpenet** [comment]
Actually it's by design You can use bulk with es/execute but we set the default header to application/json for the most common uses and _bulk expects application/x-ndjson. So either you set the header manually or better you could use es/bulk-chan, which would be the prefered way to do bulk requests and does this for you.

**Comment by faxm0dem** [comment]
thanks!
